### PR TITLE
Expense Screens Update: register, list, edit screens complete. [overwrite & updated_at need to be fixed]

### PR DESCRIPTION
**Pull request by edward-stalley-work**
…ed_at need to be fixed

# Pull Request Review Comments

## Overview
- **Purpose of the PR**:
    - [ ] Feature addition
    - [ ] Updated List Screen so Edit and Update and Delete are possible.
    - [ ] Register screen updated [added new inputs]
   
Needs to be implemented
    - [ ] Overwrite function working
    - [ ] updated_at working

## Specific Areas for Verification
- Please specify any particular requests or questions for the reviewer here.

## Suggestions/Concerns
- If you have any suggestions or concerns, please mention them here.

---

_**Additional Comments for the Reviewer (Optional)**_

- Add any additional comments or information for the reviewer here.

### CODE REVIEW

**Comment by merlouduron** [comment]
Required to fill all inputs on registration. A message will pop-up that will say All inputs are required. The message is available along with it's translation. 
image

**Comment by edward-stalley-work** [comment]
Fixed. Added popup validation message

**Comment by edward-stalley-work** [comment]
Also changed Registration English Labels to 'singular' by updating financial_words files.
So rent expenses becomes rent expense

**Comment by merlouduron** [comment]
Pop up validation is okay but please not let the page to reload after closing the pop-up. 
image

Also, the inputted data must not be visible in the url. 
image

**Comment by edward-stalley-work** [comment]
Fixed Issues

**Pull request merged**
